# Generated by Django 4.0.6 on 2022-07-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('amount', models.PositiveIntegerField(verbose_name='количество')),
                ('description', models.TextField(verbose_name='описание')),
                ('weight', models.PositiveIntegerField(verbose_name='вес')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('img', models.ImageField(upload_to='', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
