# Generated by Django 4.0.6 on 2022-08-03 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('amount', models.PositiveIntegerField(verbose_name='количество')),
                ('composition', models.TextField(default=None, verbose_name='состав')),
                ('weight', models.PositiveIntegerField(verbose_name='вес')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('image', models.ImageField(upload_to='img/app_shop/product_images', verbose_name='фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
