# Generated by Django 4.0.6 on 2022-08-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, default=None, verbose_name='состав'),
        ),
    ]
