# Generated by Django 4.1 on 2022-09-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/app_shop/product_images', verbose_name='фото'),
        ),
    ]
