version: "3.9"

services:
  db:
    image:
      postgres:14.5
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  web: &web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/NinjaSushi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
      - celery_beat
      - celery_worker
  rabbitmq:
    image: rabbitmq:3.11
  celery_worker:
    <<: *web
    command: celery -A NinjaSushi worker --loglevel=info
    ports: []
    depends_on:
      - rabbitmq
      - db
      - celery_beat
  celery_beat:
    build: .
    command: celery -A NinjaSushi beat --loglevel=info --max-interval=999999
    depends_on:
      - rabbitmq
      - db

