# Generated by Django 4.1 on 2022-09-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, verbose_name='день рождения'),
            preserve_default=False,
        ),
    ]
