# Generated by Django 4.1 on 2022-09-11 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_shop', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, verbose_name='электронная почта')),
                ('phone_number', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('street', models.CharField(max_length=50, verbose_name='улица')),
                ('house', models.PositiveIntegerField(verbose_name='дом')),
                ('flat', models.PositiveIntegerField(verbose_name='квартира')),
                ('floor', models.PositiveIntegerField(blank=True, verbose_name='этаж')),
                ('intercom', models.CharField(blank=True, max_length=20, verbose_name='домофон')),
                ('payment_method', models.CharField(choices=[('card_c', 'Оплата картой курьеру'), ('cash', 'Оплата наличными курьеру')], default='card_c', max_length=6, verbose_name='способ оплаты')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('paid', models.BooleanField(default=False, verbose_name='заказ оплачен')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_orders.order', verbose_name='заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='app_shop.product', verbose_name='товар')),
            ],
        ),
    ]
