# Generated by Django 4.0.6 on 2022-08-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='электронная почта'),
            preserve_default=False,
        ),
    ]
