# Generated by Django 4.0.6 on 2022-08-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0002_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card_o', 'Оплата картой онлайн'), ('card_c', 'Оплата картой курьеру'), ('cash', 'Оплата наличными курьеру')], default='card_o', max_length=6, verbose_name='способ оплаты'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
