# Generated by Django 4.1 on 2022-09-05 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletteremail',
            options={'verbose_name': 'email для рассылки', 'verbose_name_plural': 'email для рассылки'},
        ),
    ]
