name: ninja_sushi
on: [pull_request, push]
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Adding environment variables to .env..
        run: |
          echo DEBUG=0 >> .env
          echo DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} >> .env
      - name: Setting up dev-project..
        run: docker compose up -d
      - name: Unit testing..
        run: docker compose exec web python manage.py test .
      - name: Flake8 installing..
        run: docker compose exec web pip install flake8
      - name: Flake8 testing..
        run: docker compose exec web flake8 --extend-ignore=E501 .
  deployment:
    runs-on: ubuntu-latest
    needs: test_project
    steps:
      - name: Deploying project via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/app/NinjaSushi
            git pull https://github.com/Wesson1337/NinjaSushi
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up --build -d
            docker-compose -f docker-compose.prod.yml exec web python manage.py collectstatic --noinput
            docker image prune -f
